---
version: 2
jobs:
  build-and-deploy:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout

      - restore_cache:
          keys:
            - gradle-cache

      - run:
          name: Fetch dependencies
          command: ./gradlew dependencies --refresh-dependencies

      - run:
          name: Run gradle build
          command: ./gradlew clean test shadowJar jpi -PbuildVersion="{{ .Environment.CIRCLE_SHA1 }}" --stacktrace

      - save_cache:
          key: gradle-cache
          paths:
            - ~/.gradle

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build and push Docker image
          command: |
            cd ./scripts
            chmod +x *.sh
            case ${CIRCLE_BRANCH} in
                master)
                    ./docker-build.sh -l latest
                    ./release-trigger.sh
                    ;;
                develop)
                    ./docker-build.sh -l beta
                    ;;
                *)
                    echo "No release required for branch: ${CIRCLE_BRANCH}"
                    ;;
            esac

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy
